version: 0.2    
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS 
      - curl  https://dotnet.microsoft.com/en-us/download/dotnet/7.0/.MSbuild.sh | bash /dev/stdin --channel STS 
  build:
    commands:
      - dotnet restore eShopOnWeb/eShopOnWeb.sln
      - dotnet build eShopOnWeb/eShopOnWeb.sln
