version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build
      - dotnet run
      - dotnet publish -c release -o ./build_output 
artifacts:
  files:
    - build_output/**/*
    - scripts/**/*
    - appspec.yml
    
