version: 0.2    
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS
	  - chmod +x /install
	  - sudo install auto
	  - sudo service eShopOnWeb status
  build:
    commands:
      - dotnet restore eShopOnWeb/eShopOnWeb.sln
      - dotnet build  eShopOnWeb/eShopOnWeb.sln
artifacts:
  files:
    - build_output/**/*
    - scripts/**/*
    
