version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore /eShopOnWeb/src/BlazorShared/BlazorShared.csproj
  build:
    commands:
      - echo Build started on `date`  
      - dotnet publish -c release -o ./eShopOnWeb/src/BlazorShared/BlazorShared.csproj
artifacts:
  files:
    - /**/*
    - /**/*
