version: 0.2    
phases:
  pre_build:
    commands:
       - dotnet restore BlazorApp.csproj
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS 
      - dotnet restore BlazorApp.csproj
  build:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y dotnet-runtime-7.0
      - dotnet publish -c release -o ./build_output BlazorApp.csproj
      - dotnet restore eShopOnWeb/eShopOnWeb.sln
      - dotnet build eShopOnWeb/eShopOnWeb.sln
      
